SELECT 
    REG_ANS AS operadora, 
    SUM(VL_SALDO_FINAL) AS total_despesa,
    DESCRICAO,
    DATA
FROM relatorio_contabil
WHERE DESCRICAO = 'EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR '
AND DATA >= DATE_SUB(CURDATE(), INTERVAL 12 MONTH)
GROUP BY REG_ANS,DESCRICAO,DATA
ORDER BY total_despesa DESC
LIMIT 10;